name = "zola-hacker"
description = "Hacker is a theme for Zola"
license = "MIT"
homepage = "https://github.com/en9inerd/zola-hacker"
min_version = "0.19.1"
demo = "https://zola-hacker.enginerd.io/"

[author]
name = "Duarte Pedro Pinto"
homepage = "https://github.com/dpnpinto"

[original]
author = "Github Pages"
homepage = "https://dpnpinto.github.io"
repo = "https://github.com/dpnpinto"

[extra]
