name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.CV_KEY }}

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build with Zola
        uses: shalzz/zola-deploy-action@v0.22.1
        env:
          PAGES_BRANCH: main
          BUILD_ONLY: true

      - name: Deploy to dpnpinto.github.io
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.PAGES_DEPLOY_KEY }}
          external_repository: dpnpinto/dpnpinto.github.io
          publish_branch: main
          publish_dir: ./public
